import type { Metadata } from "next";
import { Geist, Geist_Mono, Handlee } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import StoreProvider from "@/components/client/StoreProvider";
import ThemeProvider from "@/components/client/ThemeProvider";

const handlee = Handlee({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-handlee",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${handlee.variable} antialiased`}
      >
        <StoreProvider>
          <ThemeProvider>
            {children}
            {modal}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
