import type { Metadata } from "next";
import { Geist, Geist_Mono, Handlee } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";

const handlee = Handlee({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-handlee",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${handlee.variable} antialiased`}
      >
        <div className="md:flex flex-row-reverse">
          {children}
          <SideBar />
        </div>
      </body>
    </html>
  );
}
